### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by aarontan-git** [ros-planning/navigation_tutorials#16]
Hello,

I am wondering, what does the following line mean in the simple navigation goals code?

`goal.target_pose.pose.orientation = tf::createQuaternionMsgFromYaw(M_PI);`

thank you,
Aaron

**Comment by mikeferguson** [comment]
It is setting the orientation of the goal to be in the horizontal plane with an angle of PI radians.

**Comment by DLu** [comment]
Please ask questions like this on answers.ros.org in the future.
