### ISSUE TITLE
Launch files fail because of reference to pre-hydro "stage" package.

### ISSUE THREAD

**Issue by hershwg** [ros-planning/navigation_tutorials#2]
in groovy, one can

rosrun stage stageros

in hydro, that is

rosrun stage_ros stageros

This breaks launch files which use stage.

Files in https://github.com/ros-planning/navigation_tutorials/tree/groovy-devel/navigation_stage/launch need to be updated.

Originally reported here: https://github.com/ros-planning/navigation/issues/101

**Comment by wjwwood** [comment]
This is no longer an issue in the `indigo-devel` branch.
