### ISSUE TITLE
let robot auto explores its surrounding and mapping without manually giving a goal

### ISSUE THREAD

**Issue by robbiedood** [ros-planning/navigation_tutorials#21]
Dear navigation_tutorials friends,

As far as we know, the navigation stack requires a given goal in order to start a navigation. We were wondering if the stack allows robot automatically explore its surrounding and mapping. (such as greedy frontier exploration).

Since we are new on ros-planning/navigation pkgs, hope to hear your expertise on the issue.

Thanks,
-- Luke

**Comment by DLu** [comment]
Hi Luke!

In general, answers.ros.org is probably a better starting place for this type of question. A quick search for `ros robot exploration` turned up [this](https://wiki.ros.org/rrt_exploration)
