### ISSUE TITLE
Wrong pose in .world files

### ISSUE THREAD

**Issue by gustavovelascoh** [ros-planning/navigation_tutorials#3]
Due to fixes on stage (stage_ros) coordinate systems, poses of map and robots in .world files are wrong, and is not possible to set a goal because laser frames appears out of map. I have been working with multi-robot example and these are the lines that I fixed in willow-pr2-multi.world file (uncommented lines are the corrected positions):

```
#pose [ -26.300 29.200 0 90.000 ]
pose [ 29.200 26.300 0 0 ]

...

#pr2( pose [ -21.670 47.120 0 28.166 ] name "pr2_0" color "blue")
#pr2( pose [ -21.670 48.120 0 28.166 ] name "pr2_1" color "green")
#block( pose [ -24.269 48.001 0 180.000 ] color "red")

pr2( pose [ 47.120 21.670 0 28.166 ] name "pr2_0" color "blue")
pr2( pose [ 48.120 21.670 0 28.166 ] name "pr2_1" color "green")
block( pose [ 48.001 24.269 0 180.000 ] color "red")
```

I suposse that all .world files need to be fixed.

Thanks.

**Comment by wjwwood** [comment]
@gustavovelascoh sorry, I know it's been a long time (I don't think anyone was watching this repository), but if you still have interest in this please consider a pull request. I'd do it for you, but I'm not entirely sure I understand what you're suggesting we change in the world files.

I'm going to close for now, feel free to comment though and I can reopen it if needed.

Thanks.
