### ISSUE TITLE
Extra build_depends in stage packages

### ISSUE THREAD

**Issue by cottsay** [ros-planning/navigation_tutorials#4]
I'm pretty sure none of these `build_depend`s are necessary:
- https://github.com/ros-planning/navigation_tutorials/blob/hydro-devel/roomba_stage/package.xml#L19-L22
- https://github.com/ros-planning/navigation_tutorials/blob/hydro-devel/navigation_stage/package.xml#L21-L26

**Comment by wjwwood** [comment]
Addressed on the indigo-devel branch at least:
- f11f187fe1da44e4f5d43c95f4816f590e209548
- d0e72408448d8c4d7d7bc1943e9208b02300dfcc
